# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399762934fa845d30699c9ee19227c722c016d0c63df61e3e23ee3915b94e7257afef5cd61a91424130a91c3d839ea958b5cd03fab2ae525c820bb21ed6aa2e1

test:
  secret_key_base: 0aaefc1f2ea1a0201190d039d0d66a2ef92fb6a78aca15e7da685ee3d9032ea4dfd37aa17ace9c85e3df3a019fd19c22f8e49ae49b2d2b81db02428b86fbfbf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
